# Generated by Django 4.0.4 on 2022-06-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_title_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
